FROM rocker/shiny-verse:latest

# system libraries of general use
RUN apt-get update && apt-get install -y \
    sudo \
    pandoc \
    pandoc-citeproc \
    libcurl4-gnutls-dev \
    libcairo2-dev \
    libxt-dev \
    libssl-dev \
    libssh2-1-dev

COPY . /

WORKDIR /

# select port
EXPOSE 3838

CMD R -e 'shiny::runApp("global.R", port = 3838, host = "0.0.0.0")'