# base image
FROM rocker/shiny-verse:latest

# Install required R packages
RUN R -e "install.packages(c('shinymanager', 'DBI', 'RSQLite'))"

COPY . /

WORKDIR /

EXPOSE 3838

CMD R -e 'shiny::runApp("app.R", port = 3838, host = "0.0.0.0")'